version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 14
    command:
        # Install packages or any pre-reqs in this phase
        # Upgrading SAM CLI to LAtest Version
        - pip3 install --upgrade awscli
        # - pip3 install --upgrade aws-sam-cli
        # - sam --version
        # - npm ci --producation=false
        # - npm run build:tsc
  build:
    commands:
      # use Build phase to build your artifacts (compile, etc.)
      - aws cloudformation deploy --template-file ./templates/cloudfront-s3-bucket.yaml --stack-name mydemoproject-app-$ENV_STAGE-cloudfront-s3-bucket --s3-bucket $DEPLOYMENT_BUCKET_NAME --parameter-overrides $(cat myproject-app-cloudfront-s3-bucket.$ENV_STAGE.properties) --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset

# artifacts:
#   files:
#     - template.yaml